# permissions for end users to view exchangeratewatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: forex-operator
    app.kubernetes.io/managed-by: kustomize
  name: exchangeratewatcher-viewer-role
rules:
- apiGroups:
  - forex.jannawro.dev
  resources:
  - exchangeratewatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - forex.jannawro.dev
  resources:
  - exchangeratewatchers/status
  verbs:
  - get
